apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::851725603941:user/TempUser
      username: TempUser
      groups:
        - system:masters 

