apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-viewer-binding
subjects:
- kind: Group
  name: TempUser  # The user defined in IAM and referenced in aws-auth
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-viewer
  apiGroup: rbac.authorization.k8s.io

